[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.clangd]
command = "clangd"
args = ["--background-index", "--clang-tidy"]

# Python

[[language]]
name = "python"
language-servers = ["pyright"]
auto-format = true
formatter = { command = "black", args = ["--quiet", "-"] }
indent = { tab-width = 4, unit = "    " }

# Rust

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format = true
formatter = { command = "rustfmt", args = ["--edition", "2021"] }
indent = { tab-width = 4, unit = "    " }

[language-server.rust-analyzer.config.check]
command = "clippy"

# C

[[language]]
name = "c"
language-servers = ["clangd"]
auto-format = true
formatter = { command = "clang-format" }
indent = { tab-width = 4, unit = "    " }

# C++

[[language]]
name = "cpp"
language-servers = ["clangd"]
auto-format = true
formatter = { command = "clang-format" }
indent = { tab-width = 4, unit = "    " }
